#设置虚拟机操作间隔 单位：
vm_hz: 20

#VMWARE主机
vc:
    vc_ip: 172.16.56.10
    vc_acount: administrator@vsphere.local
    vc_pwd: 1qaz@WSX
    flag: sgxyvcenter
#  vc2:
#    vc_ip: 172.16.56.12
#    vc_acount: root
#    vc_pwd: 1qaz@WSX
#    flag: sgxy02
#  vc3:
#    vc_ip: 172.16.56.13
#    vc_acount: root
#    vc_pwd: 1qaz@WSX
#    flag: sgxy03
#  vc4:
#    vc_ip: 172.16.56.14
#    vc_acount: root
#    vc_pwd: 1qaz@WSX
#    flag: sgxy04
#  vc5:
#    vc_ip: 172.16.56.15
#    vc_acount: root
#    vc_pwd: 1qaz@WSX
#    flag: sgxy05
#  vc6:
#    vc_ip: 172.16.56.16
#    vc_acount: root
#    vc_pwd: 1qaz@WSX
#    flag: sgxy06
#  vc7:
#    vc_ip: 172.16.56.17
#    vc_acount: root
#    vc_pwd: 1qaz@WSX
#    flag: sgxy07
#  vc8:
#    vc_ip: 172.16.56.18
#    vc_acount: root
#    vc_pwd: 1qaz@WSX
#    flag: sgxy08
#  vc9:
#    vc_ip: 172.16.56.19
#    vc_acount: root
#    vc_pwd: 1qaz@WSX
#    flag: sgxy09
#  vc10:
#    vc_ip: 172.16.56.20
#    vc_acount: root
#    vc_pwd: 1qaz@WSX
#    flag: sgxy10
#  vc11:
#    vc_ip: 172.16.56.21
#    vc_acount: root
#    vc_pwd: Xuanyuan@123
#    flag: sgxy11
#  vc12:
#    vc_ip: 172.16.56.22
#    vc_acount: root
#    vc_pwd: Xuanyuan@123
#    flag: sgxy12

#汇捷后台wtc数据库
hj_db:
  db_host: 172.16.56.47
  db_user: root
  db_pwd: 1qaz@WSX
  db_port: 3306
  db: hj4_backend
